stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - cmake -S code -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - ctest --test-dir build --output-on-failure
  dependencies:
    - build

package:
  stage: package
  script:
    - cmake --build build --target package
  artifacts:
    # Adjust the pattern as needed (CPack will generate an installer/archive, e.g., .zip)
    paths:
      - build/*.zip
  dependencies:
    - build
    - test
  only:
    - main
