#pragma once

#include "EFRAPIBindings.h"

namespace EventfulEngine{
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(Texture_SRV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(Texture_UAV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(TypedBuffer_SRV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(TypedBuffer_UAV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(StructuredBuffer_SRV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(StructuredBuffer_UAV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(RawBuffer_SRV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(RawBuffer_UAV)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(ConstantBuffer)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(VolatileConstantBuffer)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(Sampler)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(RayTracingAccelStruct)
    EF_BINDING_LAYOUT_ITEM_INITIALIZER(SamplerFeedbackTexture_UAV)

#undef EF_BINDING_LAYOUT_ITEM_INITIALIZER
} // EventfulEngine
